# Generated by Django 4.1.11 on 2023-10-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_author_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
