# Generated by Django 4.1.11 on 2023-10-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
